name: Docker CIs with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar          

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push Docker image
        with:
          image: danielsabana/componente-patrones
          tags: ${{ env.GIT_SHA_SHORT }}
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: ${{ secrets.CLAVE }}

      - name: Update Version in Deployment
        run: |
          git clone https://github.com/dani-saavedra/componente-patrones-k8s.git && cd componente-patrones-k8s/ 
          sed -i '' "s|image: [^ ]*|image: danielsabana/componente-patrones:v1|" componente-patrones-deployment.yaml  
          git commit -m "Update deployment image"
          git push

