name: Docker CIs with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push Docker image
        with:
          image: danielsabana/componente_patrones
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: ${{ secrets.CLAVE }}
      - name: Clone deployment repository
        env:
          EXTERNAL_REPO: 'https://github.com/dani-saavedra/componente-patrones-k8s.git'
          BRANCH: 'main'
        run: |
          git clone --single-branch --branch ${{ env.BRANCH }} ${{ env.EXTERNAL_REPO }} componente-patrones-k8s
          cd componente-patrones-k8s
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.3
      - name: Set new image tag
        env:
          IMAGE_NAME: danielsabana/componente_patrones
          NEW_TAG: ${{ env.GIT_SHA_SHORT }}
        run: |
          cd componente-patrones-k8s
          yq eval ".spec.template.spec.containers[0].image = \"${{ env.IMAGE_NAME }}:${{ github.sha }}\"" -i componente-patrones-deployment.yaml
      - name: Commit changes in external repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd componente-patrones-k8s
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actualiza imagen a ${{ env.IMAGE_NAME }}:${{ github.sha }}"
          git remote set-url origin https://dani-saavedra:${{ env.GITHUB_TOKEN }}@github.com/dani-saavedra/componente-patrones-k8s.git
          git push origin main
          

