name: Docker CIs with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
env:
  new_version: $((${{ secrets.VERSION }}+1))
  old_version: ${{ secrets.VERSION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar          

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - name: Docker login
        env:
          DOCKER_USERNAME: danielsabana
          DOCKER_PASSWORD: ${{ secrets.CLAVE }}
        run : docker login -u="danielsabana" -p="Daniel.28" docker.io
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag danielsabana/componente_patrones:$((new_version))
      - name: Publish dockerImage to docker hub
        run: docker push danielsabana/componente_patrones:$((new_version))

      - name: Update Version in Helm
        run: |
          git@github.com:dani-saavedra/componente-patrones-k8s.git
          sed -i "s/image: $((old_version))/tag: $((new_version))/" values.yaml
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Commit and Push Changes
        uses: actions-js/push@master
        with:
          directory: helm-chart
          github_token: ${{ secrets.TOKEN }}
          repository: software-unisabana/helm-chart
          message: Version updated ${date}

      - name: Update Version Number
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'VERSION'
          value: $new_version
          repository: software-unisabana/app-example-k8s
          token: ${{ secrets.TOKEN }}
